name: Create Deployment PR

inputs:
  app-name:
    description: 'The name of the app to deploy'
    required: true
  release-version:
    description: 'The release version to deploy'
    required: true
  argocd-file:
    description: 'The ArgoCD file to deploy'
    required: true
  repo-token:
    required: true
    description: Token to access x-deployk8s repo

runs:
  using: 'composite'
  steps:
    - name: Setup yq
      uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: 'v4.45.2'

    - name: Checkout x-deployk8s Repository
      uses: actions/checkout@v4
      with:
        repository: hungp29/x-deployk8s
        token: ${{ inputs.repo-token }}
        github-server-url: "https://github.com"
        fetch-depth: 1
    
    - name: Update target version
      shell: bash
      run: |
        yq -i '
          .spec.source.targetRevision = "${{ inputs.release-version }}"
        ' applications/${{ inputs.argocd-file }}

    - name: Set pr title and body
      id: set-pr-title-and-body
      shell: bash
      run: |
        VERSION="${{ inputs.release-version }}"
        APP="${{ inputs.app-name }}"
        FILE="${{ inputs.argocd-file }}"

        echo "pr_title=chore($APP): update target revision to $VERSION" >> $GITHUB_OUTPUT
        echo "pr_body=Auto-generated PR to update target revision to \`$VERSION\` for \`$APP\` in \`$FILE\`" >> $GITHUB_OUTPUT

    - name: Create Branch
      shell: bash
      run: |
        git checkout -B chore/update-${{ inputs.app-name }}-${{ inputs.release-version }}

    - name: Commit Changes
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add applications/${{ inputs.argocd-file }}
        git commit -m "${{ steps.set-pr-title-and-body.outputs.pr_title }}" -m "${{ steps.set-pr-title-and-body.outputs.pr_body }}" || echo "No changes"

    - name: Push Changes
      shell: bash
      run: |
        git push origin "chore/update-${{ inputs.app-name }}-${{ inputs.release-version }}"

    - name: Create PR
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
      shell: bash
      run: |
        gh pr create \
          --repo hungp29/x-deployk8s \
          --base main \
          --head "chore/update-${{ inputs.app-name }}-${{ inputs.release-version }}" \
          --title "${{ steps.set-pr-title-and-body.outputs.pr_title }}" \
          --body "${{ steps.set-pr-title-and-body.outputs.pr_body }}"